### ISSUE TITLE
The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later

### ISSUE THREAD

**Issue by Quintisimo** [adieuadieu/serverless-chrome#139]
I am very new to serverless and headless chrome. I keep geting this error when I deploy my function on aws lambda. Could someone please point me in the right direction to fix this
```javascript
START RequestId: a3324bd2-705a-11e8-b3bb-731eba449111 Version: $LATEST
2018-06-15 15:12:05.147 (+10:00)        a3324bd2-705a-11e8-b3bb-731eba449111    @serverless-chrome/lambda: Spawning headless shell
2018-06-15 15:12:05.153 (+10:00)        a3324bd2-705a-11e8-b3bb-731eba449111    @serverless-chrome/lambda: ChromeLauncher No debugging port found on port 9222, launching a new Chrome.
2018-06-15 15:12:05.176 (+10:00)        a3324bd2-705a-11e8-b3bb-731eba449111    @serverless-chrome/lambda: Launcher Chrome running with pid 12 on port 9222.
2018-06-15 15:12:05.176 (+10:00)        a3324bd2-705a-11e8-b3bb-731eba449111    @serverless-chrome/lambda: Waiting for Chrome 0
2018-06-15 15:12:05.679 (+10:00)        a3324bd2-705a-11e8-b3bb-731eba449111    @serverless-chrome/lambda: Waiting for Chrome 1
2018-06-15 15:12:05.680 (+10:00)        a3324bd2-705a-11e8-b3bb-731eba449111    @serverless-chrome/lambda: Started Chrome
2018-06-15 15:12:05.680 (+10:00)        a3324bd2-705a-11e8-b3bb-731eba449111    @serverless-chrome/lambda: It took 533ms to spawn chrome.
Fri, 15 Jun 2018 05:12:05 GMT HeadlessChrome:chrome Launching Chrome instance. Headless: YES
Fri, 15 Jun 2018 05:12:05 GMT HeadlessChrome:chrome Launching Chrome. Attempt 1/3...
which: no google-chrome-stable in (/var/lang/bin:/usr/local/bin:/usr/bin/:/bin)
which: no google-chrome in (/var/lang/bin:/usr/local/bin:/usr/bin/:/bin)
Fri, 15 Jun 2018 05:12:05 GMT HeadlessChrome:chrome Can't launch Chrome in attempt 1/3. Error code: undefined Error: The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.
    at Object.linux (/var/task/node_modules/chrome-launcher/chrome-finder.js:105:15)
    at Launcher.<anonymous> (/var/task/node_modules/chrome-launcher/chrome-launcher.js:109:75)
    at Generator.next (<anonymous>)
    at /var/task/node_modules/chrome-launcher/chrome-launcher.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/var/task/node_modules/chrome-launcher/chrome-launcher.js:8:12)
    at Launcher.launch (/var/task/node_modules/chrome-launcher/chrome-launcher.js:94:16)
    at Object.<anonymous> (/var/task/node_modules/chrome-launcher/chrome-launcher.js:42:24)
    at Generator.next (<anonymous>)
    at /var/task/node_modules/chrome-launcher/chrome-launcher.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/var/task/node_modules/chrome-launcher/chrome-launcher.js:8:12)
    at Object.launch (/var/task/node_modules/chrome-launcher/chrome-launcher.js:32:12)
    at Object._callee$ (/var/task/node_modules/simple-headless-chrome/build/chrome.js:74:35)
    at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:303:22)
END RequestId: a3324bd2-705a-11e8-b3bb-731eba449111
REPORT RequestId: a3324bd2-705a-11e8-b3bb-731eba449111  Duration: 617.94 ms     Billed Duration: 700 ms        Memory Size: 1024 MB    Max Memory Used: 94 MB

START RequestId: 89bfdf8a-705e-11e8-8ace-8bd587a04dd8 Version: $LATEST
which: no google-chrome-stable in (/var/lang/bin:/usr/local/bin:/usr/bin/:/bin)
which: no google-chrome in (/var/lang/bin:/usr/local/bin:/usr/bin/:/bin)
which: no chromium-browser in (/var/lang/bin:/usr/local/bin:/usr/bin/:/bin)
which: no chromium in (/var/lang/bin:/usr/local/bin:/usr/bin/:/bin)
2018-06-15 15:40:00.681 (+10:00)        89bfdf8a-705e-11e8-8ace-8bd587a04dd8    {"errorMessage":"The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.","errorType":"Error","stackTrace":["Object.linux (/var/task/node_modules/chrome-launcher/dist/chrome-finder.js:108:15)","Launcher.<anonymous> (/var/task/node_modules/chrome-launcher/dist/chrome-launcher.js:139:80)","Generator.throw (<anonymous>)","rejected (/var/task/node_modules/chrome-launcher/dist/chrome-launcher.js:10:65)","<anonymous>","process._tickDomainCallback (internal/process/next_tick.js:228:7)"]}
END RequestId: 89bfdf8a-705e-11e8-8ace-8bd587a04dd8
REPORT RequestId: 89bfdf8a-705e-11e8-8ace-8bd587a04dd8  Duration: 117.93 ms     Billed Duration: 200 ms        Memory Size: 1024 MB    Max Memory Used: 67 MB

START RequestId: f78fe045-7061-11e8-a72f-257e60136745 Version: $LATEST
which: no google-chrome-stable in (/var/lang/bin:/usr/local/bin:/usr/bin/:/bin)
which: no google-chrome in (/var/lang/bin:/usr/local/bin:/usr/bin/:/bin)
END RequestId: f78fe045-7061-11e8-a72f-257e60136745
REPORT RequestId: f78fe045-7061-11e8-a72f-257e60136745  Duration: 580.76 ms     Billed Duration: 600 ms        Memory Size: 1024 MB    Max Memory Used: 60 MB

START RequestId: fe074da0-7061-11e8-97d1-834125659352 Version: $LATEST
2018-06-15 16:04:41.089 (+10:00)        fe074da0-7061-11e8-97d1-834125659352    @serverless-chrome/lambda: Spawning headless shell
2018-06-15 16:04:41.090 (+10:00)        fe074da0-7061-11e8-97d1-834125659352    @serverless-chrome/lambda: It took 1ms to spawn chrome.
which: no google-chrome-stable in (/var/lang/bin:/usr/local/bin:/usr/bin/:/bin)
which: no google-chrome in (/var/lang/bin:/usr/local/bin:/usr/bin/:/bin)
END RequestId: fe074da0-7061-11e8-97d1-834125659352
REPORT RequestId: fe074da0-7061-11e8-97d1-834125659352  Duration: 51.94 ms      Billed Duration: 100 ms        Memory Size: 1024 MB    Max Memory Used: 62 MB
```

**Comment by adieuadieu** [comment]
What does your code look like? I can't really tell from the error log, but it seems like perhaps you're trying to launch chrome with chrome-launcher. That won't work.

**Comment by jbuck94** [comment]
Was there any resolution to this? I am experience the same error
