### ISSUE TITLE
ECONNRESET and socket hang up

### ISSUE THREAD

**Issue by SeanBE** [adieuadieu/serverless-chrome#194]
This is probably related to #79, #41 .
I'm getting the following on at least every other lambda invocation:
```
Error occured in serverless-plugin-chrome wrapper when trying to ensure Chrome for default() handler. { functions: [ 'get-content' ],
  flags: [ '--window-size=1280,1696', '--hide-scrollbars' ] } { Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  response: undefined }
```
I'm closing the chrome instance at the end of invocation like suggested [here](https://github.com/adieuadieu/serverless-chrome/issues/149#issuecomment-409254515).

```javascript
module.exports.default = async (event, context, callback, chrome) => {

  try {
    // ...handle query arguments from event
  
    const response = await request
      .get(`${chrome.url}/json/version`)
      .set("Content-Type", "application/json");
    const endpoint = response.body.webSocketDebuggerUrl;

    browser = await puppeteer.connect({
      browserWSEndpoint: endpoint
    });

    // do stuff with puppeteer and return result
  } catch (e) {
    // handle potential failures else throw error again.
  } finally {
    // close puppeteer browser object.
    // ....
    await chrome.kill();
  }
};
```
I'm running `serverless-plugin-chrome@1.0.0-55`  on `nodejs8.10` runtime. I'm not running with the `DEBUG` flag set. I've tried modifying the kill function as mentioned in #186 as well as launching chrome again with the `@serverless-chrome/lambda` module. With the latter, I get the same # of failures but with a socket hang up. 

Am I doing something wrong or should I continue debugging?

**Comment by SeanBE** [comment]
I couldn't get to the root cause. I ending up switching  back to `nodejs6.10` runtime with the `chrome-remote-interface` lib.
