### ISSUE TITLE
chromedriver unexpectedly exited

### ISSUE THREAD

**Issue by darrenhakimi** [adieuadieu/serverless-chrome#213]
I am running the exact code from the github repo. I built it used the steps in the Makefile. I am getting the below error:
`python3 src/lambda_function.py 
Traceback (most recent call last):
  File "src/lambda_function.py", line 27, in <module>
    test()
  File "src/lambda_function.py", line 8, in test
    driver = WebDriverWrapper()
  File "/working/build/src/webdriver_wrapper.py", line 48, in __init__
    self._driver = webdriver.Chrome(chrome_options=chrome_options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127`

I am running it for a Docker amazonlinux image. I tried using the below versions:
`chromedriver 2.43
severless-chrome 1.0.0-55
selenium 3.14`

`chromedriver 2.44
severless-chrome 1.0.0-55
selenium 3.14`

`chromedriver 2.32
severless-chrome 1.0.0-29
selenium 3.14`

None have worked. All gave the same listed error. I would greatly appreciate your help.

**Comment by mknycha** [comment]
Not sure if the versions you have mentioned are compatible. Have you tried `chromedriver 2.37` with `serverless-chrome 1.0.0.41`? As per [this article](https://hackernoon.com/running-selenium-and-headless-chrome-on-aws-lambda-layers-python-3-6-bd810503c6c3), these should work.
