### ISSUE TITLE
Error Chromedriver unexpectedly exited. Status code was: 127

### ISSUE THREAD

**Issue by AboveTheHeavens** [adieuadieu/serverless-chrome#246]
Hello, 

I'm using python 3.6, selenim 3.14 , headless-chrome 1.0.0-37 and chromedriver 2.37.
I've also tried it with headless-chrome 1.0.0-55 and chromedriver 2.43/2.44

I just keep getting this erro

`Traceback (most recent call last):
  File "lambda_function.py", line 31, in <module>
    title = lambda_handler(None, None)
  File "lambda_function.py", line 22, in lambda_handler
    "./bin/chromedriver", chrome_options=options)
  File "/home/red/notebooks/AWS_Selenium/lambda_headless_chrome_python/lambda_headless_chrome_python/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/red/notebooks/AWS_Selenium/lambda_headless_chrome_python/lambda_headless_chrome_python/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/red/notebooks/AWS_Selenium/lambda_headless_chrome_python/lambda_headless_chrome_python/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service ./bin/chromedriver unexpectedly exited. Status code was: 127`

I'm not sure, what I am doing wrong, can someone help me please?

**Comment by jrpvt** [comment]
I got this combo to work with both python 3.6 and python 3.7 runtimes:
- selenium 3.14
- headless-chrome 1.0.0-55
- chromedriver 2.43

The python 3.8 runtime didn't work with the config listed above.  I tried using chromedriver 2.44 with python 3.7 but couldn't get it to launch.  Hopefully 2.43 will work for you.  As a side note, make sure selenium is 3.14 and not 3.141 (latest as of today).

**Comment by syunkevichdemandbase** [comment]
@jrpvt Thank you so much. Moving from python3.8 to python3.6 completely solved my problem!

**Comment by SmileSydney** [comment]
Just wondering if there's a combination that will work for Python 3.8?

**Comment by xoxwgys56** [comment]
i hope there is someone who succeed with Python 3.8. i really don't know
