### ISSUE TITLE
Getting ENOENT error message

### ISSUE THREAD

**Issue by eddiekollar** [adieuadieu/serverless-chrome#25]
I'm running:
`"@serverless-chrome/lambda": "0.0.0-pre-release-5"`

After redeploying a new version of a function I started seeing this error message:
```
Error: spawn /var/task/node_modules/@serverless-chrome/lambda/dist/headless_shell ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Code snippet from handler:
```
const launchChrome = require('@serverless-chrome/lambda');
const CDP = require('chrome-remote-interface');

module.exports.chrome = (event, context, callback) => {
  let sourceURL = event.sourceURL;
  let destURL = event.destURL;
  console.log(sourceURL, destURL);

  if(!sourceURL || !destURL){
    const msg = 'Missing arguments';
    console.error(msg);
    callback(null, {
      statusCode: 500,
      body: JSON.stringify({
        error: msg
      })
    });
    return;
  }
  
  console.log('launching headless Chrome');
  launchChrome({
    flags: ['--window-size=1280x1696', '--hide-scrollbars']
  })
  .then((chrome) => {
    //Other code
    callback(null, {
      statusCode: 200,
      body: JSON.stringify({
        message: 'Command successfully!'
       })
   });
  }).catch((error) => {
    callback(null, {
      statusCode: 500,
      body: JSON.stringify({
        error: error
      })
    });
  });
};
```
I removed and then recreated the Lambda function again. 

Anyone else seeing this?

**Comment by adieuadieu** [comment]
Hi @eddiekollar Do you continue to experience the issue if you upgrade to the latest version of `@serverless-chrome/lambda`?

**Comment by eddiekollar** [comment]
I had ended up installing `@serverless-chrome/lambda@1.0.0-4` which works fine.

**Comment by adieuadieu** [comment]
@eddiekollar great; glad to hear the issue is resolved.
