### ISSUE TITLE
SEVERE: Issue running latest chromium on AWS Lambda

### ISSUE THREAD

**Issue by apathan123** [adieuadieu/serverless-chrome#250]
I am struggling to resolve this issue while running latest version of my script in Lambda written in java.  Not even sure what more information is needed to make this question more sensible. Any help will be appreciated, 
I get following error:
0000000000f  si: 000000000000000f  bp: 00007ffd98089370  bx: 00007ffd980893e0
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007fe4894643a7  sp: 00007ffd98089238
  ip: 00007fe4894643a7 efl: 0000000000000206 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 000000000000000c
[end of stack trace]
Calling _exit(1). Core file will not be generated.
Feb 03, 2020 4:38:10 PM org.openqa.selenium.os.UnixProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'HOST IP ', ip: 'HOST IP', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.138-99.102.amzn2.x86_64', java.version: '1.8.0_201'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:159)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:148)
	at demotest.BaseFunc.initialize(BaseFunc.java:163)
	at demotest.DemoInput.handleRequest(DemoInput.java:95)
	at demotest.DemoInput.handleRequest(DemoInput.java:1)
	at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:178)
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:906)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341)
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)
Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'HOST IP', ip: 'HOST IP', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.138-99.102.amzn2.x86_64', java.version: '1.8.0_201'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:178)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:166)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:78)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 16 more
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:26382/status] to be available after 20001 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:107)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:175)
	... 19 more
Caused by: com.google.common.util.concurrent.UncheckedTimeoutException: java.util.concurrent.TimeoutException
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:140)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:80)
	... 20 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:128)
	... 21 more
END RequestId: 61c7c40a-d43f-4645-af78-102666c4022f
REPORT RequestId: 61c7c40a-d43f-4645-af78-102666c4022f	Duration: 23085.07 ms	Billed Duration: 23100 ms	Memory Size: 3008 MB	Max Memory Used: 299 MB	Init Duration: 1015.82 ms

**Comment by adieuadieu** [comment]
New release now [available](https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-57).
