### ISSUE TITLE
Post install script fails for v1.0.0-57

### ISSUE THREAD

**Issue by HanXHX** [adieuadieu/serverless-chrome#281]
Hi,

The postinstall script fails to download Chrome...

Expected link to use:

https://github.com/adieuadieu/serverless-chrome/releases/download/v1.0.0-57/stable-headless-chromium-amazonlinux-2.zip

Link used (404 error):

https://github.com/adieuadieu/serverless-chrome/releases/download/v1.0.0-57/stable-headless-chromium-amazonlinux-2017-03.zip

Cheers,

EM

```
root@6914ac1b0f46:/app# yarn add @serverless-chrome/lambda                 
yarn add v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "serverless > @serverless/components > inquirer-autocomplete-prompt@1.2.0" has unmet peer dependency "inquirer@^5.0.0 || ^6.0.0 || ^7.0.0".
warning "serverless-webpack > ts-node@9.0.0" has unmet peer dependency "typescript@>=2.7".
[4/4] Building fresh packages...
error /app/node_modules/@serverless-chrome/lambda: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /app/node_modules/@serverless-chrome/lambda
Output:
Downloading precompiled headless Chromium binary (stable channel) for AWS Lambda.
Error: HTTP 404: Could not download https://github.com/adieuadieu/serverless-chrome/releases/download/v1.0.0-57/stable-headless-chromium-amazonlinux-2017-03.zip
    at ClientRequest.<anonymous> (/app/node_modules/@serverless-chrome/lambda/scripts/postinstall.js:54:25)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by adieuadieu** [comment]
Should be fixed in @serverless-chrome/lambda@1.0.0-57.2 ...
