### ISSUE TITLE
Update to Python 3.9

### ISSUE THREAD

**Issue by paulocoutinhox** [adieuadieu/serverless-chrome#342]
Hi,

Can you update to Python 3.9?

Im getting this error:

```
[ERROR] WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127

Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 80, in lambda_handler
    driver = webdriver.Chrome(chrome_options=chrome_options)
  File "/opt/python/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/opt/python/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/opt/python/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
```

Thanks.

**Comment by selected-pixel-jameson** [comment]
Seeing as how AWS has now removed 3.6 support it seems as if the only compatible version is 3.7 based on other issues that I've read. Hopefully this will be looked at so that we at least have 3.7 & 3.8 support.  In any case some updates would be awesome.
