### ISSUE TITLE
Unable to start chrome error

### ISSUE THREAD

**Issue by iamakimmer** [adieuadieu/serverless-chrome#52]
What could be causes of this? For the same url, it seems to fail randomly saying unable to start chrome. In some cases there is no error. 

2017-08-03T19:07:25.905Z	f995197a-787e-11e7-9309-41d30aecb3f9	Unhandled rejection Error: Unable to start Chrome. If you have the DEBUG env variable set,there will be more in the logs.
    at /var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:304:13
    at throw (native)
    at step (/var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:257:191)
    at /var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:257:402
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by adieuadieu** [comment]
Hi @iamakimmer — Could you share more of the log? You might be running into the same issue described in #41. Try the temporary work-around solution proposed in https://github.com/adieuadieu/serverless-chrome/issues/41#issuecomment-317989508.

**Comment by iamakimmer** [comment]
Sure, here is the full log:
```


d=4aaa0870-f174-4130-986f-a18cb6205b54; path=/; httponly
[0803/191444.362653:VERBOSE7:cookie_monster.cc(1766)] SetCookie() key: mysite.net cc: name: session_id value: 4aaa0870-f174-4130-986f-a18cb6205b54 domain: theme1.mysite.net path: / creation: 1501787684
[0803/191444.978031:INFO:CONSOLE(0)] "-webkit-linear-gradient is deprecated. Please use linear-gradient instead.", source:  (0)
[0803/191444.978195:INFO:CONSOLE(0)] "-webkit-gradient is deprecated. Please use linear-gradient or radial-gradient instead.", source:  (0)
[0803/191447.737248:VERBOSE7:cookie_monster.cc(1728)] SetCookie() line: raygun4js-userid=90059023-4414-0280-9687-3440f31d0736; expires=Sun, 03 Sep 2017 19:14:47 GMT; path=/
[0803/191447.737308:VERBOSE7:cookie_monster.cc(1766)] SetCookie() key: mysite.net cc: name: raygun4js-userid value:  domain: theme1.mysite.net path: / creation: 1501787687
[0803/191448.737037:VERBOSE7:cookie_monster.cc(1728)] SetCookie() line: __cfduid=dc6879cf5f1a0f0e595b56c03e791aae81501787688; expires=Fri, 03-Aug-18 19:14:48 GMT; path=/; domain=.browser-update.org; HttpOnly
[0803/191448.737105:VERBOSE7:cookie_monster.cc(1766)] SetCookie() key: browser-update.org cc: name: __cfduid value: dc6879cf5f1a0f0e595b56c03e791aae81501787688 domain: .browser-update.org path: / creation: 1501787688
[0803/191454.777129:VERBOSE7:cookie_monster.cc(1728)] SetCookie() line: _ga=GA1.2.1117026849.1501787695; path=/; expires=Sat, 03 Aug 2019 19:14:54 GMT; domain=90059023-4414-0280-9687-3440f31d0736.net;
[0803/191454.777201:VERBOSE7:cookie_monster.cc(1766)] SetCookie() key: 90059023-4414-0280-9687-3440f31d0736.net cc: name: _ga value: GA1.2.1117026849.1501787695 domain: .90059023-4414-0280-9687-3440f31d0736.net path: / creation: 1501787694
[0803/191454.777518:VERBOSE7:cookie_monster.cc(1728)] SetCookie() line: _gid=GA1.2.1685114890.1501787695; path=/; expires=Fri, 04 Aug 2017 19:14:54 GMT; domain=90059023-4414-0280-9687-3440f31d0736.net;
[0803/191454.777549:VERBOSE7:cookie_monster.cc(1766)] SetCookie() key: 90059023-4414-0280-9687-3440f31d0736.net cc: name: _gid value: GA1.2.1685114890.1501787695 domain: .90059023-4414-0280-9687-3440f31d0736.net path: / creation: 1501787694
[0803/191454.857404:VERBOSE7:cookie_monster.cc(1728)] SetCookie() line: _gat=1; path=/; expires=Thu, 03 Aug 2017 19:15:54 GMT; domain=90059023-4414-0280-9687-3440f31d0736.net;
[0803/191454.857473:VERBOSE7:cookie_monster.cc(1766)] SetCookie() key: 90059023-4414-0280-9687-3440f31d0736.net cc: name: _gat value: 1 domain: .90059023-4414-0280-9687-3440f31d0736.net path: / creation: 1501787694

2017-08-03T19:26:22.217Z	9ef01d73-7881-11e7-af01-d7913202c4f7	Unhandled rejection Error: Unable to start Chrome. If you have the DEBUG env variable set,there will be more in the logs.
    at /var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:304:13
    at throw (native)
    at step (/var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:257:191)
    at /var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:257:402
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
END RequestId: 9ef01d73-7881-11e7-af01-d7913202c4f7
```

Will attempt the workaround

**Comment by adieuadieu** [comment]
Hi @iamakimmer hm.. Could you enable the `DEBUG=*` environment flag?
